"use client";
import React from 'react';
import styles from './UsesofAI.module.css';

const AcceptableUsesOfAISection = () => {
  return (
    <>
      <div className={styles.termsContent}>
        <div className="container">
          <div className={styles.termsWrapper}>
            <section className={styles.termsSection}>
              <h2 className={styles.termsHeading}>Acceptable Uses of AI</h2>
              <div className={styles.termsText}>
                <p>
                  At <span className="highlight-brand">Do My Ebook</span>, we embrace innovation while prioritizing originality and your unique vision. With the rapid evolution of AI tools, we want to be completely transparent about how Artificial Intelligence can and cannot be used in creating your content.
                </p>
              </div>
            </section>

            <section className={styles.termsSection}>
              <h2 className={styles.termsHeading}>Our Approach to AI</h2>
              <div className={styles.termsText}>
                <p>
                  Our core commitment is to deliver custom, high-quality content that truly reflects your ideas. We understand that AI can be a powerful tool, and we allow its use only under specific, controlled conditions to support our creatives, not replace them.
                </p>
                <p>
                  <span className="highlight-brand">Do My Ebook</span> may utilize AI-powered tools internally to assist our team in the creative process, such as:
                </p>
                <div className={styles.servicesList}>
                  <div className={styles.serviceItem}>
                    <span className={styles.serviceBullet}>•</span>
                    <span><span className="highlight-important">Generating Ideas:</span> Helping brainstorm concepts for characters, plot points, settings, or thematic elements.</span>
                  </div>
                  <div className={styles.serviceItem}>
                    <span className={styles.serviceBullet}>•</span>
                    <span><span className="highlight-important">Refining Content:</span> Assisting with grammar checks, spelling, phrasing, and ensuring consistency.</span>
                  </div>
                  <div className={styles.serviceItem}>
                    <span className={styles.serviceBullet}>•</span>
                    <span><span className="highlight-important">Research Support:</span> Aiding in gathering information and source materials.</span>
                  </div>
                </div>
                <p>
                  However, it&apos;s crucial that any AI-generated content is always significantly modified and reviewed by a human professional to ensure its accuracy, relevance, appropriateness, accessibility, and, most importantly, its originality and alignment with your specific project requirements.
                </p>
              </div>
            </section>

            <section className={styles.termsSection}>
              <h2 className={styles.termsHeading}>Your Consent is Key</h2>
              <div className={styles.termsText}>
                <p>
                  The use of any AI tool for content generation on your specific project is strictly prohibited unless we have received your express permission to do so. If we believe an AI tool could enhance a specific aspect of your project (e.g., for idea generation), we will seek your direct approval first.
                </p>
                <p>
                  Please note: If you choose to allow the use of AI in your project, you agree that any content generated by our internal AI systems may be used for machine learning purposes to improve the quality and relevance of our content over time. We always protect your privacy, ensuring any data used for training is collected with your consent and in accordance with applicable laws.
                </p>
              </div>
            </section>

            <section className={styles.termsSection}>
              <h2 className={styles.termsHeading}>Third-Party AI Detection Tools</h2>
              <div className={styles.termsText}>
                <p>
                  We understand the concern about AI-generated content. However, third-party AI detection tools do not always provide accurate or complete results. They are not infallible, and their findings do not automatically mean content is plagiarized or requires revision.
                </p>
                <p>
                  Our revision policy, as outlined <a href="/refund-revision-policy" className={styles.contactEmail}>here</a>, does not permit requesting changes to your document based solely on the findings of third-party AI detection tools or speculation about AI use. Our focus for revisions remains on ensuring the content meets your original project requirements and our quality standards.
                </p>
                <p>
                  If you suspect any unauthorized or improper use of AI tools in your project, please contact our Platform Support team. We will conduct a thorough review and discuss the findings and options with you.
                </p>
              </div>
            </section>

            <section className={styles.termsSection}>
              <h2 className={styles.termsHeading}>Our Ethical Commitment</h2>
              <div className={styles.termsText}>
                <p>
                  At <span className="highlight-brand">Do My Ebook</span>, we are dedicated to the ethical and responsible use of AI. Our commitment includes:
                </p>
                <div className={styles.servicesList}>
                  <div className={styles.serviceItem}>
                    <span className={styles.serviceBullet}>•</span>
                    <span><span className="highlight-important">Transparency:</span> Being clear about how and when AI is used.</span>
                  </div>
                  <div className={styles.serviceItem}>
                    <span className={styles.serviceBullet}>•</span>
                    <span><span className="highlight-important">Accuracy:</span> Striving for accurate content based on reliable information.</span>
                  </div>
                  <div className={styles.serviceItem}>
                    <span className={styles.serviceBullet}>•</span>
                    <span><span className="highlight-important">Privacy:</span> Protecting your data and using it only with your consent and in compliance with regulations.</span>
                  </div>
                  <div className={styles.serviceItem}>
                    <span className={styles.serviceBullet}>•</span>
                    <span><span className="highlight-important">Accountability:</span> Taking responsibility for content generated with AI and regularly reviewing our systems.</span>
                  </div>
                </div>
              </div>
            </section>

            <section className={styles.termsSection}>
              <h2 className={styles.termsHeading}>Consequences of Misuse</h2>
              <div className={styles.termsText}>
                <p>
                  To maintain our high standards, our creatives are strictly prohibited from:
                </p>
                <div className={styles.servicesList}>
                  <div className={styles.serviceItem}>
                    <span className={styles.serviceBullet}>•</span>
                    <span>Using AI tools on your project without your express permission.</span>
                  </div>
                  <div className={styles.serviceItem}>
                    <span className={styles.serviceBullet}>•</span>
                    <span>Inputting sensitive or confidential customer information (like personal details, pen names, or publishing information) into AI tools.</span>
                  </div>
                  <div className={styles.serviceItem}>
                    <span className={styles.serviceBullet}>•</span>
                    <span>Running content written for <span className="highlight-brand">Do My Ebook</span> through third-party AI detection tools.</span>
                  </div>
                </div>
                <p>
                  Any creative who breaches this policy will be removed from the <span className="highlight-brand">Do My Ebook</span> platform, and their account will be deactivated.
                </p>
                <p>
                  As AI technology continues to evolve, <span className="highlight-brand">Do My Ebook</span> reserves the right to update this policy to reflect new developments and concerns at any time.
                </p>
              </div>
            </section>
          </div>
        </div>
      </div>
    </>
  );
};

export default AcceptableUsesOfAISection;
